//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_NoiThatViwood
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.CTHoaDon = new HashSet<CTHoaDon>();
        }
    
        public string MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public long TongTien { get; set; }
        public string MaNV { get; set; }
        public string MaDonDat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDon { get; set; }
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
