//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_NoiThatViwood
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_QLCH_02Entities2 : DbContext
    {
        public DB_QLCH_02Entities2()
            : base("name=DB_QLCH_02Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTDonDatHang> CTDonDatHang { get; set; }
        public virtual DbSet<CTNhapHang> CTNhapHang { get; set; }
        public virtual DbSet<CTHoaDon> CTHoaDon { get; set; }
        public virtual DbSet<DonDatHang> DonDatHang { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<NhapHang> NhapHang { get; set; }
        public virtual DbSet<Nhom> Nhom { get; set; }
        public virtual DbSet<PhongBan> PhongBan { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<vw_DSChiTietDonDatHang> vw_DSChiTietDonDatHang { get; set; }
        public virtual DbSet<vw_DSDonDatHang> vw_DSDonDatHang { get; set; }
        public virtual DbSet<vw_DSNhapHang> vw_DSNhapHang { get; set; }
        public virtual DbSet<vw_DSCTNhapHang> vw_DSCTNhapHang { get; set; }
        public virtual DbSet<vw_DSHoaDon> vw_DSHoaDon { get; set; }
    }
}
