//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_NoiThatViwood
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DSHoaDon
    {
        public string MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public long TongTien { get; set; }
        public string HoTen { get; set; }
        public string MaDonDat { get; set; }
        public string HoTenKH { get; set; }
    }
}
